FROM bemcom/python-connector-template:0.1.0

# Place your dependencies here. E.g:
RUN pip install pymodbus==2.4.*

# Export your connector script. Ensure the main program of the
# connector resides under ./source/connector/main.py
COPY ./connector/ /source/connector/




