# Generated by Django 2.2.5 on 2020-04-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='allowed_values',
            field=models.TextField(default='[]', help_text='Allowed values. Applicable to discrete valued datapoints. Must be a valid JSON string.'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='max_value',
            field=models.FloatField(blank=True, default=None, help_text='The maximal expected value of the datapoint. Applicable to numeric datapoints.', null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='min_value',
            field=models.FloatField(blank=True, default=None, help_text='The minimal expected value of the datapoint. Applicable to numeric datapoints.', null=True),
        ),
    ]
