# Generated by Django 2.2.5 on 2020-04-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200402_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'permissions': [('rest_get_dp_value', 'Can read a datapoints value msg via the REST API.'), ('rest_put_dp_value', 'Can write a datapoints value msg via the REST API. (For actuators only).'), ('rest_get_dp_schedule', 'Can read a datapoints schedule msg via the REST API. (For actuators only).'), ('rest_put_dp_schedule', 'Can write a datapoints schedule msg via the REST API. (For actuators only).'), ('rest_get_dp_setpoint', 'Can read a datapoints setpoint msg via the REST API. (For actuators only).'), ('rest_put_dp_setpoint', 'Can write a datapoints setpoint msg via the REST API. (For actuators only).')]},
        ),
    ]
