# Generated by Django 2.2.5 on 2019-10-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
