FROM bemcom/node-red-connector-template:0.1.0

# Export your flows to the flows folder. They will be installed on startup.
COPY ./flows /flows

# Place your dependencies here. E.g:
# RUN npm install node-red-node-ui-table@0.2.2


