from rest_framework import serializers

from api_main.models.datapoint import Datapoint


class DatapointSerializer(serializers.ModelSerializer):
    """
    Serializer matching the fields of the Datapoint model of the API.
    """
    __doc__ = None
    connector = serializers.StringRelatedField()

    class Meta:
        model = Datapoint
        fields = [
            "id",
            "connector",
            "key_in_connector",
            "type",
            "data_format",
            "short_name",
            "description",
            "min_value",
            "max_value",
            "allowed_values",
            "unit",
            ]
        # The values of these fields are internally generated by the
        # API service and the respective connector service. We don not
        # wish that any external program overloads these, However, they
        # might be necessary to match meta data to datapoints.
        read_only_fields = [
            "id",
            "connector",
            "key_in_connector",
        ]
        # Removes the unique constriant from the serializer as we do
        # only updating and the short name is very likely to exist already.
        extra_kwargs = {
                    'short_name': {
                        'validators': [],
                    }
                }
