# Generated by Django 2.2.5 on 2020-01-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, unique=True, verbose_name='Connector name')),
                ('mqtt_topic_logs', models.TextField(default=None, unique=True, verbose_name='MQTT topic for logs')),
                ('mqtt_topic_heartbeat', models.TextField(default=None, unique=True, verbose_name='MQTT topic for heartbeat')),
                ('mqtt_topic_available_datapoints', models.TextField(default=None, unique=True, verbose_name='MQTT topic for available datapoints')),
                ('mqtt_topic_datapoint_map', models.TextField(default=None, unique=True, verbose_name='MQTT topic for datapoint map')),
                ('mqtt_topic_raw_message_to_db', models.TextField(default=None, unique=True, verbose_name='MQTT topic for raw message to database')),
                ('mqtt_topic_raw_message_reprocess', models.TextField(default=None, unique=True, verbose_name='MQTT topic for reprocess')),
                ('mqtt_topic_datapoint_message_wildcard', models.TextField(default=None, unique=True, verbose_name='MQTT topic for all datapoint messages (wildcard)')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_as', models.CharField(choices=[('not used', 'Not used'), ('numeric', 'Numeric'), ('text', 'Text')], default='not used', max_length=8)),
                ('type', models.CharField(default=None, editable=False, max_length=8)),
                ('key_in_connector', models.TextField(editable=False)),
                ('example_value', models.CharField(editable=False, max_length=30)),
                ('connector', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Connector')),
            ],
        ),
        migrations.CreateModel(
            name='NumericDatapointAddition',
            fields=[
                ('datapoint', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_interface.Datapoint')),
                ('last_value', models.FloatField(editable=False, help_text='The last value received via MQTT.', null=True)),
                ('last_timestamp', models.DateTimeField(editable=False, help_text='The timestamp of the last value received via MQTT.', null=True)),
                ('min_value', models.FloatField(blank=True, default=None, help_text='The minimal expected value of the datapoint. Is uesed for automatically scaling plots.', null=True)),
                ('max_value', models.FloatField(blank=True, default=None, help_text='The maximal expected value of the datapoint. Is uesed for automatically scaling plots.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextDatapointAddition',
            fields=[
                ('datapoint', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_interface.Datapoint')),
                ('last_value', models.TextField(editable=False, help_text='The last value received via MQTT.', null=True)),
                ('last_timestamp', models.DateTimeField(editable=False, help_text='The timestamp of the last value received via MQTT.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(editable=False)),
                ('msg', models.TextField(default='', editable=False, verbose_name='Log message')),
                ('emitter', models.TextField(default='', editable=False)),
                ('level', models.SmallIntegerField(choices=[(10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], editable=False)),
                ('connector', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Connector')),
            ],
            options={
                'verbose_name_plural': 'Connector log entries',
            },
        ),
        migrations.CreateModel(
            name='ConnectorHeartbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(editable=False)),
                ('next_heartbeat', models.DateTimeField(editable=False)),
                ('connector', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Connector')),
            ],
            options={
                'verbose_name_plural': 'Connector heartbeats',
            },
        ),
    ]
