# Generated by Django 2.2.5 on 2019-11-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mqtt_topic_logs', models.TextField()),
                ('mqtt_topic_heartbeat', models.TextField()),
                ('mqtt_topic_available_datapoints', models.TextField()),
                ('mqtt_topic_datapoint_map', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_virtual', models.BooleanField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Connector')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.DeviceType')),
            ],
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Device')),
                ('unit', models.ForeignKey(on_delete=models.SET(''), to='admin_interface.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('msg', models.TextField()),
                ('emitter', models.TextField()),
                ('level', models.SmallIntegerField()),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Connector')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorHearbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField()),
                ('next_heartbeat', models.DateTimeField()),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Connector')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorAvailableDatapoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint_type', models.CharField(max_length=8)),
                ('datapoint_key_in_connector', models.TextField()),
                ('datapoint_example_value', models.TextField()),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Connector')),
            ],
        ),
    ]
