# Generated by Django 3.0 on 2019-12-10 15:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.TextField(default='', help_text='Human readable device manufacturer or service provider. E.g. Aquametro', max_length=30)),
                ('slug', models.SlugField(default='', max_length=40)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField(default='', help_text='Version/model of device, e.g. 2.1', max_length=30)),
                ('slug', models.SlugField(default='', max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='ConnectorHearbeat',
            new_name='ConnectorHeartbeat',
        ),
        migrations.AlterModelManagers(
            name='device',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='datapointunit',
            old_name='unit_qunatity',
            new_name='unit_quantity',
        ),
        migrations.AddField(
            model_name='connectoravailabledatapoints',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.TextField(default='', help_text='Name of device, e.g. Dachs', max_length=30),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='slug',
            field=models.SlugField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='friendly_name',
            field=models.TextField(default='', help_text='Human readable device description. E.g. room thermostat or heat meter', max_length=30),
        ),
    ]
