# Generated by Django 3.0 on 2019-12-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0002_auto_20191210_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_location_friendly_name',
            new_name='Device_location',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_type_friendly_name',
            new_name='Device_type',
        ),
    ]
