# Generated by Django 3.0 on 2019-12-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0003_auto_20191210_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_maker',
            field=models.ForeignKey(default='', on_delete=models.SET(''), to='admin_interface.DeviceMaker'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_slug',
            field=models.SlugField(default='device-xy', max_length=150),
        ),
        migrations.AddField(
            model_name='device',
            name='device_version',
            field=models.ForeignKey(blank=True, default='', on_delete=models.SET(''), to='admin_interface.DeviceVersion'),
        ),
    ]
