# Generated by Django 3.0 on 2019-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0004_auto_20191210_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_slug',
            field=models.SlugField(default='<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.TextField>_<django.db.models.fields.related.ForeignKey>', max_length=150),
        ),
    ]
