# Generated by Django 3.0 on 2019-12-11 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0005_auto_20191210_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 12, 11)),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_available_datapoints',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_datapoint_map',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_heartbeat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_logs',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
