# Generated by Django 3.0 on 2019-12-12 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0006_auto_20191211_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='mqtt_topic_datapoint_message_wildcard',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='connector',
            name='mqtt_topic_raw_message_reprocess',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='connector',
            name='mqtt_topic_raw_message_to_db',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='connector',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 12, 12)),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_heartbeat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(default='test-connector', max_length=50),
        ),
    ]
