# Generated by Django 3.0 on 2019-12-17 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0007_auto_20191212_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 12, 17), verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_available_datapoints',
            field=models.CharField(default='', max_length=100, verbose_name='MQTT topic for available datapoints'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_datapoint_map',
            field=models.CharField(default='', max_length=100, verbose_name='MQTT topic for datapoint map'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_datapoint_message_wildcard',
            field=models.CharField(default='', max_length=100, verbose_name='MQTT topic for all datapoint messages (wildcard)'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_heartbeat',
            field=models.CharField(default='', max_length=100, verbose_name='MQTT topic for heartbeat'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_logs',
            field=models.CharField(default='', max_length=100, verbose_name='MQTT topic for logs'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_raw_message_reprocess',
            field=models.CharField(default='', max_length=100, verbose_name='MQTT topic for reprocess'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='mqtt_topic_raw_message_to_db',
            field=models.CharField(default='', max_length=100, verbose_name='MQTT topic for raw message to database'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(default='test-connector', max_length=50, verbose_name='Connector name'),
        ),
    ]
