# Generated by Django 3.1.5 on 2021-03-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapointvalue',
            name='value_float',
            field=models.FloatField(blank=True, default=None, help_text='Similar to value but an internal float representation for numeric datapoints.', null=True),
        ),
    ]
