# Generated by Django 3.1.5 on 2021-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0002_datapointvalue_value_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='example_value',
            field=models.TextField(editable=False, help_text='One example value for this datapoint. Should help admins while mangeing datapoints, i.e. to specify the correct data format.'),
        ),
    ]
