# Generated by Django 3.1.7 on 2021-03-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0003_auto_20210303_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='short_name',
            field=models.TextField(blank=True, default=None, help_text='A short name to identify the datapoint.', max_length=30, null=True, unique=True),
        ),
    ]
