# Generated by Django 3.1.5 on 2022-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0004_auto_20220208_1927'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datapoint',
            name='Datapoint key_in_connector and connector unique together',
        ),
        migrations.AddConstraint(
            model_name='datapoint',
            constraint=models.UniqueConstraint(fields=('connector', 'key_in_connector', 'type'), name='Datapoint key_in_connector, connector and type unique together'),
        ),
    ]
