# Generated by Django 3.1.5 on 2021-04-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0004_auto_20210322_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='origin_description',
        ),
    ]
