# Generated by Django 3.1.13 on 2021-09-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0006_auto_20210805_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='data_format',
            field=models.CharField(choices=[('generic_numeric', 'Generic Numeric'), ('continuous_numeric', 'Continuous Numeric'), ('discrete_numeric', 'Discrete Numeric'), ('generic_text', 'Generic Text'), ('discrete_text', 'Discrete Text'), ('bool', 'Boolean'), ('unknown', 'Unknown')], default='unknown', help_text='Format of the datapoint value. Additionally defines which metadata is available for it. See documentation in code for details.', max_length=18),
        ),
    ]
