# Generated by Django 2.2 on 2020-07-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200408_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, unique=True, verbose_name='Controller name, used for display in the admin page.')),
                ('mqtt_topic_controlled_datapoints', models.TextField(default=None, unique=True, verbose_name='MQTT topic on which the controller awaits the configuration data.')),
            ],
        ),
        migrations.CreateModel(
            name='ControlledDatapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Flag if the this mapping should currently be used (i.e. be published as part of the controlled_datapoints msg to the controller).')),
                ('actuator_datapoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Datapoint')),
                ('sensor_datapoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_sensor_datapoint', to='main.Datapoint')),
            ],
        ),
    ]
