# Generated by Django 2.2.5 on 2020-07-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_controlleddatapoint_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlleddatapoint',
            name='actuator_datapoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_actuator_datapoint', to='main.Datapoint'),
        ),
    ]
