#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
"""
__version__="0.5.0"

import os
import json
import struct
import logging
from time import sleep
from threading import Lock

from dotenv import load_dotenv, find_dotenv
from pymodbus.client.sync import ModbusTcpClient
from pymodbus.exceptions import ModbusException

from pyconnector_template.pyconnector_template import SensorFlow as SFTemplate
from pyconnector_template.pyconnector_template import ActuatorFlow as AFTemplate
from pyconnector_template.pyconnector_template import Connector as CTemplate
from pyconnector_template.dispatch import DispatchInInterval


logger = logging.getLogger("pyconnector")


class SensorFlow(SFTemplate):
    """
    Bundles all functionality to handle sensor messages.

    This is a template for a SensorFlow class, i.e. one that holds all
    functions that are necessary to handle messages from the device(s)
    towards the message broker. The methods could also be implemented
    into the Connector class, but are separated to support clarity.

    Overload these functions
    ------------------------
    In order to transform this class into operational code you need
    to inherit from it and overload the following methods:
     - receive_raw_msg
     - parse_raw_msg

    Connector Methods
    -----------------
    The connector must provide the following methods to allow correct
    operation of the methods in this class:
     - _update_available_datapoints

    Connector Attributes
    --------------------
    The following attributes must be set up by the connector to
    allow these methods to run correctly:

    mqtt_client : class instance.
        Initialized Mqtt client library with signature of paho MQTT.
    SEND_RAW_MESSAGE_TO_DB : string
        if SEND_RAW_MESSAGE_TO_DB == "TRUE" will send raw message
        to designated DB via MQTT.
    MQTT_TOPIC_RAW_MESSAGE_TO_DB : string
        The topic which on which the raw messages will be published.
    datapoint_map : dict of dict.
        Mapping from datapoint key to topic. Is generated by the AdminUI.
        Looks e.e. like this:
            datapoint_map = {
                "sensor": {
                    "Channel__P__value__0": "example-connector/msgs/0001",
                    "Channel__P__unit__0": "example-connector/msgs/0002",
                },
                "actuator": {
                    "example-connector/msgs/0003": "Channel__P__setpoint__0",
                }
            }
        Note thereby that the keys "sensor" and "actuator"" must alaways be
        present, even if the child dicts are empty.
    """

    def receive_raw_msg(self, raw_data=None):
        """
        Functionality to receive a raw message from device.

        Poll the device/gateway for data and transforms this raw data
        into the format expected by run_sensor_flow. If the device/gateway
        uses some protocol that pushes data, the raw data should be passed
        as the raw_data argument to the function.

        Parameters
        ----------
        raw_data : TYPE, optional
            Raw data of device/gateway if the device pushes and is not
            pulled for data. The default is None.

        Returns
        -------
        msg : dict
            The message object containing the raw data. It must be
            JSON serializable (to allow sending the raw_message object as JSON
            object to the raw message DB). If the data received from the device
            or gateway cannot be packed to JSON directly (like e.g. for bytes)
            it must modified accordingly. Avoid manipulation of the data as much
            as possible, to prevent data losses when these operations fail.
            A simple solution may often be to cast the raw data to strings.
            Dict structures are fine, especially if created in this function,
            e.g. by iterating over many endpoints of one device.
            Should be formatted like this:
                msg = {
                    "payload": {
                        "raw_message": <raw data in JSON serializable form>
                    }
                }
            E.g.
                msg = {
                    "payload": {
                        "raw_message": "device_1:{sensor_1:2.12,sensor_2:3.12}"
                    }
                }
        """
        with self.modbus_communication_ongoing:
            if not hasattr(self, "modbus_connection"):
                # Establish connection to modbus master device.
                logger.debug(
                    "Connecting to Modbus master %s:%s",
                    *(self.modbus_master_ip, self.modbus_master_port)
                )
                self.modbus_connection = ModbusTcpClient(
                    host=self.modbus_master_ip, port=self.modbus_master_port
                )
                if not self.modbus_connection.connect():
                    raise RuntimeError("Could not connect to Modbus master.")

            # Read all data requested in configuration.
            raw_message = {k: {} for k in self.modbus_read_method_names}
            for read_method_name in self.modbus_read_method_names:
                read_method = getattr(self.modbus_connection, read_method_name)
                requested_ranges = self.modbus_config[read_method_name]
                # requested_range is an entry like:
                # {
                #     "address": 19000,
                #     "count": 20,
                #     "unit": 1,
                #     "datatypes": ">ffffffffff",
                # },
                for i, requested_range in enumerate(requested_ranges):
                    logger.debug(
                        "Using method %s to request data from address %s with "
                        "count %s from unit %s.",
                        *(
                            read_method_name,
                            requested_range["address"],
                            requested_range["count"],
                            requested_range["unit"],
                        )
                    )
                    retry = 0
                    while True:
                        response = read_method(
                            address=requested_range["address"],
                            count=requested_range["count"],
                            unit=requested_range["unit"],
                        )
                        if (
                            isinstance(response, BaseException)
                            or response.isError()
                        ):
                            # This track here is if the read failed. Then we
                            # wait a bit and retry a few times before we finally
                            #  fail. If we retried to often we raise the
                            # execption and exit.
                            logger.info(
                                "Reading from modbus device failed with "
                                "function %s for address %s. Retrying in %s "
                                "seconds. Error was: %s",
                                *(
                                    read_method_name,
                                    requested_range["address"],
                                    self.retry_wait,
                                    str(response),
                                )
                            )
                            retry += 1
                            if retry >= self.max_retries:
                                raise RuntimeError(
                                    "Max number of retries exceeded."
                                )
                            sleep(self.retry_wait)
                            continue
                        # Pack the registers/coils into the raw message.
                        elif "_registers" in read_method_name:
                            response_data = response.registers
                        else:
                            response_data = response.bits
                        raw_message[read_method_name][i] = response_data
                        break
                    # Maybe wait a bit before next request.
                    sleep(self.poll_break)

            if self.disconnect_between_polls:
                logger.debug("Disconnecting from Modbus Master.")
                self.modbus_connection.close()
                # This is required so we create a new connection next poll.
                delattr(self, "modbus_connection")

            msg = {
                "payload": {
                    "raw_message": raw_message
                }
            }
            return msg

    def parse_raw_msg(self, raw_msg):
        """
        Parses the values from the raw_message.

        This parses the raw_message into an object (in a JSON meaning, a
        dict in Python). The resulting object can be nested to allow
        representation of hierarchical data.

        Be aware: All keys in the output message should be strings. All values
        must be convertable to JSON.

        Parameters
        ----------
        raw_msg : dict.
            Raw msg with data from device/gateway. Should be formatted like:
                msg = {
                    "payload": {
                        "raw_message": <the raw data>,
                        "timestamp": <milliseconds since epoch>
                    }
                }

        Returns
        -------
        msg : dict
            The message object containing the parsed data as python dicts from
            dicts structure. All keys should be strings. All value should be
            of type string, bool or numbers. Should be formatted like this:
                msg = {
                    "payload": {
                        "parsed_message": <the parsed data as object>,
                        "timestamp": <milliseconds since epoch>
                    }
                }
            E.g:
                msg = {
                    "payload": {
                        "parsed_message": {
                            "device_1": {
                                "sensor_1": "test",
                                "sensor_2": 3.12,
                                "sensor_2": True,
                            }
                        },
                        "timestamp": 1573680749000
                    }
                }
        """
        raw_message = raw_msg["payload"]["raw_message"]
        parsed_message = {}
        for read_method_name in raw_message:
            parsed_message[read_method_name] = {}
            modbus_config_for_method = self.modbus_config[read_method_name]
            mbas_for_method = self.modbus_addresses[read_method_name]
            for i in raw_message[read_method_name]:
                # Load modbus addresses as strings as other stuff is loaded
                # from JSON and expects strings too.
                mbas = [str(m) for m in mbas_for_method[i]]

                if "_registers" in read_method_name:
                    registers = raw_message[read_method_name][i]
                    datatypes = modbus_config_for_method[i]["datatypes"]

                    # Now we going to to encode the registers (which are
                    # currently represented as 16bit int values) to bytes so
                    # we can decode the data back with the correct datatype.
                    # This approach is taken from the pymodbus code, which
                    # does the same but doesn't allow to decode all of the
                    # values at once.
                    values_b = b''.join(
                        struct.pack('!H', x) for x in registers
                    )
                    try:
                        values = struct.unpack(datatypes, values_b)
                    except struct.error:
                        logger.error(
                            "Unpacking binary data with struct failed. "
                            "The Modbus request returned %s registers, aka "
                            "%s bytes. However, you may have configured "
                            "datatypes in MODBUS_CONFIG corresponding to "
                            "a different number of bytes, see struct.error "
                            "below.",
                            *(len(registers), len(registers)*2)
                        )
                        raise

                else:
                    values = []
                    for value in raw_message[read_method_name][i]:
                        values.append(value)

                # Store each value under it's Modbus address.
                # This may overwrite values if overlapping address
                # ranges have been specified by the user.
                # Also apply scaling factors while we are here, but only
                # to registers. Scaling bits doesn't make sense, even if the
                # user would request it.
                sfs = {}
                if (
                    "scaling_factors" in modbus_config_for_method[i] and
                    "_registers" in read_method_name
                ):
                    sfs = modbus_config_for_method[i]["scaling_factors"]
                for mba, value in zip(mbas, values):
                    if mba in sfs:
                        try:
                            scaled_value = float(value) * sfs[mba]
                            value = scaled_value
                        except ValueError:
                            pass

                    # Also story data under unit to prevent name clashes
                    # if the same address is requested from two different
                    # units.
                    # Note that unit must be a string here to allow the
                    # computation of the flat internal datapoint id
                    # (aka. the key_in_connector)
                    unit = str(modbus_config_for_method[i]["unit"])
                    if unit not in parsed_message[read_method_name]:
                        parsed_message[read_method_name][unit] = {}
                    parsed_message[read_method_name][unit][mba] = value

        msg = {
            "payload": {
                "parsed_message": parsed_message,
                "timestamp": raw_msg["payload"]["timestamp"],
            }
        }
        return msg


class ActuatorFlow(AFTemplate):
    """
    Bundles all functionality to handle actuator messages.

    This is a template for a ActuatorFlow class, i.e. one that holds all
    functions that are necessary to handle messages from the message
    broker towards the devices/gateway. The methods could also be implemented
    into the Connector class, but are separated to support clarity.

    Overload these functions
    ------------------------
    In order to transform this class into operational code you need
    to inherit from it and overload the following methods:
     - send_command

    Connector Attributes
    --------------------
    The following attributes must be set up by the connector to
    allow these methods to run correctly:

    datapoint_map : dict of dict.
        Mapping from datapoint key to topic. Is generated by the AdminUI.
        Looks e.e. like this:
            datapoint_map = {
                "sensor": {
                    "Channel__P__value__0": "example-connector/msgs/0001",
                    "Channel__P__unit__0": "example-connector/msgs/0002",
                },
                "actuator": {
                    "example-connector/msgs/0003": "Channel__P__setpoint__0",
                }
            }
        Note thereby that the keys "sensor" and "actuator"" must always be
        present, even if the child dicts are empty.
    """

    def send_command(self, datapoint_key, datapoint_value):
        """
        Send message via Modbus to device.

        TODO: Add scaling factors for registers.

        Parameters
        ----------
        datapoint_key : string.
            The internal key that is used by device/gateway to identify
            the datapoint. E.g. "write_coil__1__19"
        value : string, float, bool or None.
            The value that should be sent to the datapoint.
        """
        logger.debug(
            "Starting send_command for key: %s and value: %s",
            datapoint_value,
            datapoint_key,
        )

        # Only let those datapoints pass that were configured.
        # Receiving such a key should actually be impossible. But better
        # double check.
        if datapoint_key not in self.write_config_per_datapoint_key:
            logger.warning(
                "Send command triggered for unknown datapoint_key: %s",
                datapoint_key
            )
            return

        # Now, let's go. Start with the extracting the configuration
        # for this message.
        write_config = self.write_config_per_datapoint_key[datapoint_key]
        write_method_name = write_config["write_method_name"]
        write_method = getattr(self.modbus_connection, write_method_name)

        # Second sanity check, only Bools can be send to coils.
        if "coil" in write_method_name:
            if not (datapoint_value == True or datapoint_value == False):
                logger.warning(
                    "Cannot send non Boolean value %s to coil datapoint %s",
                    datapoint_value,
                    datapoint_key,
                )
                return

        # Encode the datapoint_value to the the format expected by PyModbus.
        if "coil" in write_method_name:
            # As we know that this must be True or False already.
            encoded_value = datapoint_value
            # No special treatment for coils necessary.
            write_method_kwargs={}
        else:
            # OK, this must be a register then.
            bin = struct.pack(
                write_config["datatypes"], datapoint_value
            )
            if write_method_name == "write_registers":
                # However, PyModbus wants to have a list with two bytes
                # (=1 register) per item.
                encoded_value = [bin[i:i+2] for i in range(0, len(bin), 2)]
            else:
                # While the normal write_register takes a single value.
                encoded_value = bin
            # Tells the write method that it gets binary stuff not registers
            # formatted as unsigned ints.
            write_method_kwargs={"skip_encode": True}

            # This is an alternative implementation by Hedi.
            # builder = BinaryPayloadBuilder(
            #     byteorder=mdb_datatype[0], wordorder=Endian.Big
            # )
            # builder.reset()
            # p_string = builder._pack_words(
            #     mdb_datatype[1:], fast_real(datapoint_value)
            # )
            # builder._payload.append(p_string)
            # values = builder.to_registers()[0]


        with self.modbus_communication_ongoing:
            if not hasattr(self, "modbus_connection"):
                # Establish connection to modbus master device.
                logger.debug(
                    "Connecting to Modbus master %s:%s",
                    *(self.modbus_master_ip, self.modbus_master_port)
                )
                self.modbus_connection = ModbusTcpClient(
                    host=self.modbus_master_ip, port=self.modbus_master_port
                )
                if not self.modbus_connection.connect():
                    raise RuntimeError("Could not connect to Modbus master.")

            logger.debug(
                "Using method %s to push data to address %s with "
                "for unit %s.",
                *(
                    write_method_name,
                    write_config["address"],
                    write_config["unit"],
                )
            )
            retry = 0
            while True:
                response = write_method(
                    address=write_config["address"],
                    value=encoded_value,
                    unit=write_config["unit"],
                    **write_method_kwargs,
                )
                if (isinstance(response, BaseException) or response.isError()):
                    # This track here is if the write failed. Then we
                    # wait a bit and retry a few times before we finally
                    #  fail. If we retried to often we raise the
                    # execption and exit.
                    logger.info(
                        "Writing to modbus device failed with "
                        "function %s for address %s. Retrying in %s "
                        "seconds. Error was: %s",
                        *(
                            write_method_name,
                            write_config["address"],
                            self.retry_wait,
                            str(response),
                        )
                    )
                    retry += 1
                    if retry >= self.max_retries:
                        raise RuntimeError(
                            "Max number of retries for send_command exceeded."
                        )
                    sleep(self.retry_wait)
                    continue
                logger.debug(
                    "Received response for send_command: %s",
                    str(response)
                )
                break
            # Maybe wait a bit before next request.
            sleep(self.poll_break)

            if self.disconnect_between_polls:
                logger.debug("Disconnecting from Modbus Master.")
                self.modbus_connection.close()
                # This is required so we create a new connection next poll.
                delattr(self, "modbus_connection")


class Connector(CTemplate, SensorFlow, ActuatorFlow):
    """
    The generic logic of the connector.

    It should not be necessary to overload any of these methods nor
    to call any of those apart from __init__() and run().

    Configuration Attributes
    ------------------------
    Confiugration will be populated from environment variables on init.
    CONNECTOR_NAME : string
        The name of the connector instance as seen by the AdminUI.
    MQTT_TOPIC_LOGS : string
        The topics used by the log handler to publish log messages on.
    MQTT_TOPIC_HEARTBEAT : string
        The topics used by the connector to publish heartbeats on.
    MQTT_TOPIC_AVAILABLE_DATAPOINTS : string
        The topic on which the available datapoints will be published.
    MQTT_TOPIC_DATAPOINT_MAP : string
        The topic the connector will listen on for datapoint maps
    SEND_RAW_MESSAGE_TO_DB : string
        if SEND_RAW_MESSAGE_TO_DB == "TRUE" will send raw message
        to designated DB via MQTT. This is a string and not a bool as
        environment variables are always strings.
    MQTT_TOPIC_RAW_MESSAGE_TO_DB : string
        The topic which on which the raw messages will be published.
    DEBUG : string
        if DEBUG == "TRUE" will log debug message to, elso loglevel is info.
    MODBUS_MASTER_IP : string
        The ip adress or DNS name of the Modbus master device which we want
        to connect to.
    MODBUS_MASTER_PORT : string (as env variables are always strings)
        The port on which  the master device awaits Modbus communication.

    Computed Attributes
    -------------------
    These attributes are created by init and are then dynamically used
    by the Connector.
    mqtt_client : class instance.
        Initialized MQTT client library with signature of paho mqtt.
    available_datapoints : dict of dict.
        Lists all datapoints known to the connector and is sent to the
        AdminUI. Actuator datapoints must be specified manually. Sensor
        datapoints are additionally automatically added once a value for
        a new datapoint is received. The object contains the connector
        internal key and a sample and value looks e.g. like this:
            available_datapoints = {
                "sensor": {
                    "Channel__P__value__0": 0.122,
                    "Channel__P__unit__0": "kW",
                },
                "actuator": {
                    "Channel__P__setpoint__0": 0.4,
                }
            }
    datapoint_map : dict of dict.
        Mapping from datapoint key to topic. Is generated by the AdminUI.
        Looks e.e. like this:
            datapoint_map = {
                "sensor": {
                    "Channel__P__value__0": "example-connector/msgs/0001",
                    "Channel__P__unit__0": "example-connector/msgs/0002",
                },
                "actuator": {
                    "example-connector/msgs/0003": "Channel__P__setpoint__0",
                }
            }
        Note thereby that the keys "sensor" and "actuator"" must always be
        present, even if the child dicts are empty.
    """

    def __init__(self, *args, **kwargs):
        """
        Init the inherited code from python_connector_template and add
        function to parse the special environment variable args to configure
        this connector.

        TODO: Add support for swapping ordering of bits? Seems like our code
        works if byte order and bit are identical, i.e. both Big endian or
        both little endian. Is there a use case for other scenarios?
        """
        # dotenv allows us to load env variables from .env files which is
        # convenient for developing. If you set override to True tests
        # may fail as the tests assume that the existing environ variables
        # have higher priority over ones defined in the .env file.
        load_dotenv(find_dotenv(), verbose=True, override=False)

        # We need to specify a dispatcher that triggers the connection with
        # the device or gateway. Here we want to poll the device with the
        # interval set in the POLL_SECONDS environment variable.
        # At each poll we want to execute the full run_sensor_flow
        # As this contains all the expected logic the connector should do
        # with sensor data.
        kwargs["DeviceDispatcher"] = DispatchInInterval
        kwargs["device_dispatcher_kwargs"] = {
            "call_interval": float(os.getenv("POLL_SECONDS")),
            "target_func": self.run_sensor_flow,
        }

        # Parse MODBUS_CONFIG early as we need it to compute the actuator
        # datapoints.
        self.modbus_config = self.parse_modbus_config(
            config_json_str=os.getenv("MODBUS_CONFIG")
        )

        # Sensor datapoints will be added to available_datapoints automatically
        # once they are first appear in run_sensor_flow method. It is thus not
        # necessary to specify them here, although it would be possible to
        # compute all possible datapoints beforehand based on MODBUS_CONFIG
        caad_return = self.compute_available_actuator_datapoints(
            modbus_config=self.modbus_config
        )
        available_actuator_datapoints = caad_return[0]
        self.write_config_per_datapoint_key = caad_return[1]
        kwargs["available_datapoints"] = {
            "sensor": {},
            "actuator": available_actuator_datapoints,
        }
        CTemplate.__init__(self, *args, **kwargs)

        self.modbus_master_ip = os.getenv("MODBUS_MASTER_IP")
        self.modbus_master_port = int(os.getenv("MODBUS_MASTER_PORT"))
        self.modbus_addresses = self.compute_addresses(
            modbus_config=self.modbus_config
        )
        self.modbus_read_method_names = [
            k for k in self.modbus_config if "read_" in k
        ]
        self.max_retries = int(os.getenv("MODBUS_MAX_RETRIES") or 3)
        self.retry_wait = int(os.getenv("MODBUS_RETRY_WAIT_SECONDS") or 15)
        self.poll_break = float(os.getenv("MODBUS_POLL_BREAK") or 0)
        self.disconnect_between_polls = os.getenv("MODBUS_DISCONNECT_BETWEEN_POLLS") == "TRUE"

        # This lock should prevent that reading and writing operations
        # intervene with each other. Especially if connections are disconnected
        # in between calls.
        self.modbus_communication_ongoing = Lock()

    @staticmethod
    def parse_modbus_config(config_json_str):
        """
        Parse and verify the configuration JSON string.

        This also removes unexpected components of the config.

        Arguements:
        -----------
        config_json_str : string
            The MODBUS_CONFIG JSON string as defined in the Readme.

        Returns:
        --------
        config : dict
            The parsed version of the input.
        """
        logger.info("Parsing MODBUS_CONFIG.")

        expected_config_keys = [
            "read_coils",
            "read_discrete_inputs",
            "read_holding_registers",
            "read_input_registers",
            "write_coil",
            "write_register",
            "write_registers",
        ]

        config = json.loads(config_json_str)

        for config_key in list(config.keys()):
            if config_key not in expected_config_keys:
                logger.warning(
                    "Found unexpected key in MODBUS_CONFIG: %s"
                    "The corresponding values are:\n%s",
                    *(config_key, json.dumps(config[config_key], indent=2))
                )
                del config[config_key]

        # Check that the user has not configured the datatypes such that more
        # then one register would be send via the write_register method.
        if "write_register" in config:
            for requested_register in config["write_register"]:
                datatypes = requested_register["datatypes"]
                data_size = struct.calcsize(datatypes)
                if data_size > 2:
                    error_msg = (
                        "Configuration error in MODBUS_CONFIG. Datatype %s "
                        "implied sending %s registers while write_register "
                        "method can only used to send a single register. "
                        "The respective part of the config is: %s"
                        % (
                            datatypes,
                            data_size // 2,
                            json.dumps(requested_register)
                        )
                    )
                    logger.error(error_msg)
                    raise ValueError(error_msg)

        return config

    @staticmethod
    def compute_available_actuator_datapoints(modbus_config):
        """
        Compute the corresponding register and coil addresses to the address
        ranges specified by the user in MODBUS_CONFIG.

        Arguments:
        ----------
        modbus_config : dict
            As returned by parse_modbus_config.

        Returns:
        --------
        available_actuator_datapoints : dict
            See documentation/04_message_format.md -> Available Datapoints
        write_config_per_datapoint_key : dict
            A mapping for actuator datapoints from datapoint_key to the
            corresponding configuration dict of MODBUS_CONFIG.
        """
        available_actuator_datapoints = {}
        write_config_per_datapoint_key = {}
        for modbus_method in modbus_config:
            if modbus_method[:6] != "write_":
                continue
            for datapoint_configuration in modbus_config[modbus_method]:
                try:
                    key_in_connector = "__".join(
                        [
                            modbus_method,
                            str(datapoint_configuration["unit"]),
                            str(datapoint_configuration["address"])
                        ]
                    )
                    example_value = datapoint_configuration["example_value"]
                except KeyError:
                    logger.error(
                        "The following part of MODBUS_CONFIG does not "
                        "contain all required fields ('unit', 'address' "
                        "and 'example_value') to compute the available_"
                        "datapoints message for the actuator datapoints. "
                    )
                    logger.error(
                        "MODBUS_CONFIG (relevant part): %s -> %s",
                        json.dumps(modbus_method),
                        json.dumps(datapoint_configuration),
                    )
                    raise
                available_actuator_datapoints[key_in_connector] = example_value
                write_config = datapoint_configuration.copy()
                write_config["write_method_name"] = modbus_method
                write_config_per_datapoint_key[key_in_connector] = write_config
        return available_actuator_datapoints, write_config_per_datapoint_key

    @staticmethod
    def compute_addresses(modbus_config):
        """
        Compute the corresponding register and coil addresses to the address
        ranges specified by the user in MODBUS_CONFIG.

        Arguments:
        ----------
        modbus_config : dict
            As returned by parse_modbus_config.
        """
        # These are the Modbus functions (supported by the connector)
        # that can read a range of values.
        method_names = [
            "read_coils",
            "read_discrete_inputs",
            "read_holding_registers",
            "read_input_registers",
        ]

        # These is the mapping from the struct keys to the Modbus
        # register count, that is how many registers are filled with that
        # variable. See also:
        # https://docs.python.org/3/library/struct.html#format-characters
        char_register_size = {
            "c": 1,
            "b": 1,
            "B": 1,
            "?": 1,
            "h": 1,
            "H": 1,
            "i": 2,
            "I": 2,
            "l": 2,
            "L": 2,
            "q": 4,
            "Q": 4,
            "e": 1,
            "f": 2,
            "d": 4,
        }

        addresses = {}
        for method_name in method_names:
            if method_name not in modbus_config:
                continue

            addresses[method_name] = {}
            requested_ranges = modbus_config[method_name]

            if "register" in method_name:
                for i, requested_range in enumerate(requested_ranges):
                    # The first value starts at the start of the
                    # address range.
                    range_addresses = []
                    current_address = requested_range["address"]
                    for datatype_char in requested_range["datatypes"]:
                        if datatype_char not in char_register_size:
                            # Ignore chars defining endianess or padding.
                            continue

                        # Append the address this value starts and add it's
                        # length so we get the starting address of the next
                        # value.
                        range_addresses.append(current_address)
                        current_address += char_register_size[datatype_char]

                    # Finally store the addresses of this range under the
                    # index the range has in the config.
                    addresses[method_name][i] = range_addresses

            else:
                # Handling for read_discrete_inputs and read_coils methods,
                # is actually quite simple as every bit is exactly one bit
                # long :)
                for i, requested_range in enumerate(requested_ranges):
                    start = requested_range["address"]
                    count = requested_range["count"]
                    addresses[method_name][i] = list(range(start, start+count))

        return addresses


if __name__ == "__main__":
    connector = Connector(version=__version__)
    connector.run()
